version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "lucide"
      - dependency-name: "lucide-react"
      - dependency-name: "lucide-react-native"
